version: '3.3'

volumes:
  images:

services:
  hubot:
    build:
      context: ./cowbot
    image: fearlesstech/cowbot:cowbot
    restart: unless-stopped
    env_file:
      - .hubot.env
    links:
    - parking-service
    volumes:
    - images:/cowbot-images

  parking-service:
    build:
      context: ./parking-service
    image: fearlesstech/cowbot:parking-service
    restart: unless-stopped
    environment:
    - SCREENSHOT_PATH=/cowbot-images
    env_file:
      - .parking-service.env
    volumes:
    - images:/cowbot-images

  skill-search:
    build:
      context: ./skill-search
    restart: unless-stopped
    env_file:
      .skill-search.env
    ports:
      - "3001:3001"
    volumes:
      - ./skill-search/data/${SQLITE_DATABASE}:/app/data/${SQLITE_DATABASE}:ro

  job-refresh-skills:
    build:
      context: ./skill-search
    restart: unless-stopped
    env_file:
      .skill-search.env
    entrypoint: "node ./src/jobs/refreshSkills.js"
    volumes:
      - ./skill-search/data/${SQLITE_DATABASE}:/app/data/${SQLITE_DATABASE}:rw

  job-refresh-users:
    build:
      context: ./skill-search
    restart: unless-stopped
    env_file:
      .skill-search.env
    entrypoint: "node ./src/jobs/refreshUsers.js"
    volumes:
      - ./skill-search/data/${SQLITE_DATABASE}:/app/data/${SQLITE_DATABASE}:rw
