version: '3'
services:
  web:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - ./data/${SQLITE_DATABASE}:/app/data/${SQLITE_DATABASE}:ro
  job-refresh-skills:
    build: .
    entrypoint: "node ./src/jobs/refreshSkills.js"
    volumes:
      - ./data/${SQLITE_DATABASE}:/app/data/${SQLITE_DATABASE}:rw
  job-refresh-users:
    build: .
    entrypoint: "node ./src/jobs/refreshUsers.js"
    volumes:
      - ./data/${SQLITE_DATABASE}:/app/data/${SQLITE_DATABASE}:rw
