version: '3'
services:
  web:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./data/skill-search.db:/app/data/skill-search.db:ro
  job-refresh-skills:
    build: .
    command: "node ./src/jobs/refreshSkills.js"
    volumes:
      - ./data/skill-search.db:/app/data/skill-search.db:rw
  job-refresh-users:
    build: .
    command: "node ./src/jobs/refreshUsers.js"
    volumes:
      - ./data/skill-search.db:/app/data/skill-search.db:rw
